import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Simple autogenerated sidebar
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: ROS2',
      items: [{type: 'autogenerated', dirName: 'Module-1-ROS2'}],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      items: [{type: 'autogenerated', dirName: 'Module-2-Digital-Twin'}],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac',
      items: [{type: 'autogenerated', dirName: 'Module-3-NVIDIA-Isaac'}],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      items: [{type: 'autogenerated', dirName: 'Module-4-Vision-Language-Action'}],
    },
  ],
};

export default sidebars;
